DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS airport;

CREATE TABLE employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  surname VARCHAR(250) NOT NULL,
  firstname VARCHAR(250) NOT NULL
);

CREATE TABLE country (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  c_code VARCHAR(250) NOT NULL,
  c_name VARCHAR(250) NOT NULL
);

CREATE TABLE languages (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  l_code VARCHAR(250) NOT NULL,
  l_name VARCHAR(250) NOT NULL
);

CREATE TABLE airport (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  a_name VARCHAR(250) NOT NULL
);